#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: '3.7'
networks:
  dspacenet:
services:
  dspace:
    container_name: dspace
    depends_on:
      - dspacedb
    image: pizaini/dspace-6x-stai-tbh:1.0.1
    build:
      context: .
      dockerfile: Dockerfile.jdk8
    networks:
      dspacenet:
    ports:
      - published: 8080
        target: 8080
    stdin_open: true
    tty: true
    volumes:
      - ./dspace/src/main/docker-compose/local.cfg:/dspace/config/local.cfg
      - assetstore:/dspace/assetstore
      - solr_authority:/dspace/solr/authority/data
      - solr_oai:/dspace/solr/oai/data
      - solr_search:/dspace/solr/search/data
      - solr_statistics:/dspace/solr/statistics/data
  dspacedb:
    image: postgres:13.0
    container_name: dspacedb
    command: [ ]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rahasia
    volumes:
      - type: bind
        source: /home/pizaini/docker-volume/postgresql
        target: /var/lib/postgresql/data
    networks:
      dspacenet:
  pgadmin_dspace:
    image: dpage/pgadmin4:4.30
    container_name: pgadmin_dspace
    environment:
      PGADMIN_DEFAULT_EMAIL: zheiner.taurus@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rahasia
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: /home/pizaini/docker-volume/pgadmin
        target: /var/lib/pgadmin
    networks:
      dspacenet:
volumes:
  assetstore:
  pgdata:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics: